server:
  port: 8005

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.wancient.springcloud.api.entities.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  jpa:
    show-sql: true
  application:
    name: micro-dictionary
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/bookkeep?characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  redis:
    host: 127.0.0.1
    port: 6379
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:8761/eureka/,http://eureka7002.com:8762/eureka/,http://eureka7003.com:8763/eureka/
  instance:
    #别名
    instance-id: micro-provider-dictionary-8005
    prefer-ip-address: true     #访问路径可以显示IP地址

feign:
  hystrix:
    #开启
    enabled: true
    
info:
  app.name: wancient-micro
  company.name: www.wancient.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

# 打印mapper sql
logging:
  level:
    com.wancient.springcloud.dictionary.mapper: trace

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql